appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: XeFRO3Sdlc8Tu9T0DcdBAtQngo+Nb86MazqDHaE6owuBZct8KgVq+b4XBA8l7Opr9Yc/sxgKHhTANLtX6CwISKfq7Gbsktv+TVFc5cmddKM+KafRcQQ+il7nlThm0fUOy30YP3dNiieg189gxqYlO+TuKuIrFDGnuXWt6pKp5oeZu1194jvPAzgSfNkyEEw1lYDdK+Sk5ett2nqwmBQ19+OvlTvdIA7tU/xQqw1g3szVfEbo5VUqUpXpZwHP5W8bNkFCYfrm2zfBoRH4BGcvLc7nat+3CJEwbWxDHKneTZEn1Zf5C5qoq0t5eLPhfm4Izux5t2sJQUEIbnkxoTIhQaB60YehTkHGDf0W6ZyBx77Kc+EAB0N5ddC12OO+D2VgDDx9dAY0kpsF3i/zwuCdJo9aANuqoqUVBSyW5j7t2FINs9qjuE3GVehceAa/WrZXXbm3b6mcmAdSqPVUdfSkMsRv0JyREwGIMYak/knhpv2KzLnit/LEsUfbO9bdne7/5NjARNTa0v5kGcFBIFSX54OKt9pUnlEeehuAeQepome5syyWgDveYeRVWoY7hXhF+/tSyw5FDfdUZBLs76U2lRLbA8yPdk921EXAZ2Cyahzd0BBv2N6j+0OfZjZWl2KF1xPBGRGVKG/q01QK9iiCLv+RjiBROwfdZQm9b1EZ5G8=}
